backend:
  name: github
  repo: migmuni/personal-website
  branch: 'v2.0'
media_folder: "src/media/uploads"
public_folder: "dist/media/uploads"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "index.md"
        fields:
          - label: "Menu"
            name: "menu"
            fields:
              - label: "Class"
                name: "class"
              - label: "Main Menu"
                name: "main"
              - label: "Social Media"
                name: "social"
